name: Run R targets and tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("targets", "testthat", "RPostgres", "dplyr", "here", "withr", "DBI"))

      - name: Run tests
        run: |
          testthat::test_dir("tests")

      - name: Run pipeline
        run: |
          targets::tar_make()
  
