name: Run R targets and tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('targets', 'testthat', 'RPostgres', 'dplyr', 'here', 'withr', 'DBI', 'lintr', 'tidyr'))"

      - name: Check for lints
        run  |
          Rscript -e "lints <- lintr::lint_dir('R'); if(length(lints) > 0) { print(lints); quit(status = 1) } else { message('No lints found.') }"

      - name: Run tests
        run: |
          Rscript -e "testthat::test_dir('tests')"

      - name: Run pipeline
        run: |
          Rscript -e "targets::tar_make()"

